[package]
name = "yacrd"
version = "0.6.0"
authors = ["Pierre Marijon <pierre.marijon@inria.fr>"]

exclude = ["image/*", "validation/*", "tests/*"]

description = "Using all-against-all read mapping, yacrd performs: computation of pile-up coverage for each read and detection of chimeras"
homepage = "https://github.com/natir/yacrd"
repository = "https://github.com/natir/yacrd"
readme = "Readme.md"
license = "MIT"
keywords = ["bioinformatics", "chimera", "long-read"]

[badges]
travis-ci = { repository = "natir/yacrd", branch = "master" }

[dependencies]
bio            = "0.30"
csv            = "1"
niffler        = {git = "https://github.com/luizirber/niffler/", branch = "api_1.0"}
thiserror      = "1.0"
anyhow         = "1.0"
structopt      = "0.3"
lazy_static    = "1.0"
serde_derive   = "1.0"
enum_primitive = "0.1.1"

[profile.release]
debug = true # uncomment for proffiling
lto = 'thin'
opt-level = 3
overflow-checks = false
panic = 'abort'
incremental = false

[[bin]]
name = "yacrd"
path = "src/main.rs"
