[package]
name = "yarcd-rust"
version = "0.3.0"
authors = ["Pierre Marijon <pierre.marijon@inria.fr>"]

[dependencies]
bio = "*"
zip = "*"
csv = "1"
clap = "2.31.2"
serde = "1.0"
serde_derive = "1.0"
